### ISSUE TITLE
Add Local FS Support for Registry Service

### ISSUE THREAD

**Issue by cdarwin** [saltstack-formulas/docker-formula#11]
It may be desirable to use local fs instead of AWS S3

**Comment by nmadhok** [comment]
@cdarwin Would it be possible for you to submit a Pull Request for this? Thanks for filing the issue!

**Comment by cdarwin** [comment]
Yes, I created these issues to outline the I provements I intend to make. Feedback welcome.

**Comment by Arabus** [comment]
I'd definately support that request - using a local filebased registry comes in handy. Especially if you have docker containers you do not want to share with amazon or the nsa ;-)

Should not be that hard, just some jinja magic in the upstart script. Though if you want to support more than just debian & ubuntu you might want to move that docker run ... snippet to a general shell script or even a full blown init script.

**Comment by tiadobatima** [comment]
@cdarwin @Arabus 

With #40, the registry now becomes a lot more configurable. 

For registry 2.x:
```
registry:
  lookup:
    version: 2
    runoptions:
      - "-e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/somewhere"
      - "-v /my-registry-dir:/somewhere"
```

For *registry < 2*  you'd need to find out what the environment variables are. I made sure the formula is backwards compatible with the old pillar configs, ie when we don't specify *version*, but I haven't put much effort in testing the versioned configs with the old registry 0.9.x. It should work, but... ;)

Let me know if you find any problem
