### ISSUE TITLE
dockerfile ADD and COPY command

### ISSUE THREAD

**Issue by ghovat** [saltstack-formulas/docker-formula#117]
Hi,

why is it not possible to run a add or copy command in the formula.
I try to generate a elasticsearch container here my sls:

```
'elasticsearch master container':
  docker_container.running:
    - name: elasticsearch-master-{{ grains['id'] }}
    - image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    - restart_policy: always
    - network_mode: {{ pillar.get('ELASTICSEARCH_NETWORK', 'bridge') }}
    - user: elasticsearch
    - add: salt://containers/elasticsearch/master/files/elasticsearch.yml /usr/share/elasticsearch/config/
    - copy: salt://containers/elasticsearch/master/files/jvm.options /usr/share/elasticsearch/config/
    - volumes:
      - /srv/elasticsearch/data:/usr/share/elasticsearch/data:rw
    - __monitoring__:
      - service: container-running
      - title: elasticsearch master container
      - container_name: elasticsearch-master-{{ grains['id'] }}
```

I dont want to bind a whole folder, is there any possibility to run a add and copy command?
