### ISSUE TITLE
docker.containers doesn't restat a container after pulling an updated image

### ISSUE THREAD

**Issue by bogdanr** [saltstack-formulas/docker-formula#176]
Pillar looks like this:
```
docker-containers:
  lookup:
    zniper:
      image: "123455921830.dkr.ecr.eu-central-1.amazonaws.com/blabla:latest"
      cmd:
      pull_before_start: True
      remove_on_stop: True
      runoptions:
        - "-e MONGO_USER=staging-user"
        - "-e PORT=8000"
        - "-p 8000:8000"
      stopoptions:
        - '-t 10'
```
And running `docker.containers` pulls the updated image but it doesn't restart the container.
How can I make it restart the container when the image changes?
