### ISSUE TITLE
Why cmd.run for docker_image.present ?

### ISSUE THREAD

**Issue by Poil** [saltstack-formulas/docker-formula#191]
Hi,

Why we do this
```
{% for name, container in containers.items() %}
docker-image-{{ name }}:
  cmd.run:
    - name: docker pull {{ container.image }}
    - require:
      - service: docker-service
```

And not
```
{% for name, container in containers.items() %}
docker-image-{{ name }}:
  docker_image.present:
    - name: {{ container.image }}
    - tag: {{ container.tag }}
    - force {{ container.force_pull }} # allow to choose when doing a docker pull or not if image already exists locally
    - require:
      - service: docker-service
```

Best regards
