### ISSUE TITLE
[BUG] docker.compose-ng ports binding failure

### ISSUE THREAD

**Issue by kuznetsov420** [saltstack-formulas/docker-formula#240]
### Formula commit hash / release tag

Release Tags: `v0.43.0`, `master`

### Versions reports (master & minion)

Salt-Minion (masterless) version: 
```Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-88-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

### Pillar / config used

```
docker:
  pkg:
    install_docker_py: true
    version: 19.03.5
    use_upstream_repo: false
    compose_version: 1.25.0
    install_pypi_pip: true
  # containers:
  #   skip_translate: ports
  compose:
    nginx:
      container_name: nginx
      image: nginx
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - '80:80'
        - '443:443'
      restart: always
```

---

### Describe the bug

```
----------
          ID: nginx container
    Function: docker_container.running
        Name: nginx
      Result: False
     Comment: Failed to translate input. Additional info follows:
              
              invalid:
                  ----------
                  ports:
                      '{'80/tcp': OrderedDict([('HostPort', '80'), ('HostIp', '')]), '443/tcp': OrderedDict([('HostPort', '443'), ('HostIp', '')])}' is not a valid port definition
              
              If you feel this information is incorrect, the skip_translate argument can be used to skip input translation for the argument(s) identified as invalid. See the documentation for details.
     Started: 08:04:20.548759
    Duration: 6.987 ms
     Changes:

```

### Steps to reproduce the bug

When I tried to use this: 
```
containers:
   skip_translate: ports
```
states applied well, but:

`docker inspect nginx` (cutted down useless blocks):
```
<...>
"Config": {
            <...>
            "ExposedPorts": {
                "80/tcp": {},
                "OrderedDict([('443/tcp', OrderedDict([('HostPort', '443'), ('HostIp', '')]))])/tcp": {},
                "OrderedDict([('80/tcp', OrderedDict([('HostPort', '80'), ('HostIp', '')]))])/tcp": {}
<...>
"NetworkSettings": {
           <...>
            "Ports": {
                "0/0": null,
                "80/tcp": null
<...>
```

### Expected behaviour

`docker inspect nginx` (cutted down useless blocks):
```
<...>
"Config": {
            <...>
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
<...>
"NetworkSettings": {
           <...>
           "Ports": {
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
<...>
```
`docker port nginx`:
```
443/tcp -> 0.0.0.0:443
80/tcp -> 0.0.0.0:80
```
