### ISSUE TITLE
[BUG] compose-ng: ports statement does not allow IP address (3 column entries)

### ISSUE THREAD

**Issue by ctr49** [saltstack-formulas/docker-formula#245]
### Formula commit hash / release tag
 master / 6222d60

### Versions reports (testing in masterless mode with salt-call)
```
$ salt-call --versions-report
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 4.2.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.4 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: debian 10.4`
```

### Pillar / config used
Taken from pillar.example
```
# Docker compose supported attributes
docker:
  # install_pypi_pip: true
  # install_docker_py: true
  # version of docker-compose to install (defaults to latest)
  # compose_version: 1.9.0
  # configfile: /etc/default/docker
  install_pypi_pip: true

  # yamllint disable-line rule:line-length
  ### https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
  # daemon_config:
  #  metrics-addr: '0.0.0.0:9323'
  #  experimental: true
  #  registry-mirrors:
  #    - 'https://proxy-docker.local:5000'
  #  live-restore: true
  #  insecure-registries:
  #    - harbor.local

  pkg:
    # Package handling
    # version: 1.13.1
    # allow_updates: true
    use_upstream_app: false

  # config for sysvinit/upstart (for systemd, use drop-ins in your own states)
  config:
    - DOCKER_OPTS="-s btrfs --dns 8.8.8.8"
    - export http_proxy="http://172.17.42.1:3128"

  # PIP proxy configuration (defaults to false)
  # proxy: proxy.com:3128

  # Global functions for docker_container states
  containers:
    skip_translate: ports
    force_present: false
    force_running: true

  compose:
    registry-datastore:
      dvc: true
      # image: &registry_image 'docker.io/registry:latest' ## Fedora
      image: &registry_image 'registry:latest'
      container_name: &dvc 'registry-datastore'
      command: echo *dvc data volume container
      volumes:
        - &datapath '/registry'
    registry-service:
      image: *registry_image
      container_name: 'registry-service'
      volumes_from:
        - *dvc
      environment:
        SETTINGS_FLAVOR: 'local'
        STORAGE_PATH: *datapath
        SEARCH_BACKEND: 'sqlalchemy'
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: '/registry'
      ports:
        - 127.0.0.1:5000:5000
      # restart: 'always'    # compose v1.9
      deploy:                # compose v3
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

    nginx-latest:
      # image: 'docker.io/nginx:latest'  ##Fedora
      image: 'nginx:latest'
      container_name: 'nginx-latest'
      links:
        - 'registry-service:registry'
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - /srv/docker-registry/nginx/:/etc/nginx/conf.d
        - /srv/docker-registry/auth/:/etc/nginx/conf.d/auth
        - /srv/docker-registry/certs/:/etc/nginx/conf.d/certs
      working_dir: '/var/www/html'
      volume_driver: 'foobar'
      userns_mode: 'host'
      user: 'nginx'
      # restart: 'always'    # compose v1.9
      deploy:                # compose v3
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
```

---

### Describe the bug

Executing the state causes
```
# salt-call state.highstate test=True
[CRITICAL] Rendering SLS 'base:docker.compose-ng' failed: while parsing a block mapping
  in "<unicode string>", line 42, column 7
did not find expected key
  in "<unicode string>", line 68, column 10
local:
    Data failed to compile:
----------
    Rendering SLS 'base:docker.compose-ng' failed: while parsing a block mapping
  in "<unicode string>", line 42, column 7
did not find expected key
  in "<unicode string>", line 68, column 10
```

### Expected behaviour

Example pillar / port string with 3 statements (IP,port,port) working.

### Additional context

The example works fine when removing the IP address (127.0.0.1) from the statement, just leaving the two ports. However, I specifically want to bind to localhost.
