### ISSUE TITLE
[BUG] docker.containers requires, but does not install, yum-plugin-versionlock

### ISSUE THREAD

**Issue by anderbubble** [saltstack-formulas/docker-formula#249]
### Formula commit hash / release tag

master

### Versions reports (master & minion)

```
$ salt --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: debian 10.3
```

```
$ salt-minion --versions-report
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 4.2.1
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

### Pillar / config used

```
base:
  '[hostname]':
    - docker.containers
```

### Describe the bug

```
          ID: docker-package      
    Function: pkg.installed
        Name: docker-ce                                                                                                                         
      Result: False
     Comment: Cannot proceed, yum-plugin-versionlock is not installed.   
     Started: 23:36:22.960722
    Duration: 39598.016 ms
     Changes:   
              ----------
              installed:                             
                  ----------
                  docker-ce:                            
                      ----------
                      new:                                                        
                          3:19.03.12-3.el7
                      old:
                          3:19.03.11-3.el7
```

### Steps to reproduce the bug

- CentOS 7 install with yum-plugin-versionlock not installed.
- Use `docker.containers`

### Expected behaviour

`yum-plugin-versionlock` should either be a dependency of a salt package (whatever provides `pkg`) or installed by the `docker.containers` formula.

### Attempts to fix the bug

Installing `yum-plugin-versionlock` is successful.
