### ISSUE TITLE
[BUG] segmentation fault from dockerd on fresh Pi 4

### ISSUE THREAD

**Issue by garethhowell** [saltstack-formulas/docker-formula#264]
## Your setup
Freshlly built Raspberry Pi 4 running up to date buster
### Formula commit hash / release tag

v1.0.0 

### Versions reports (master & minion)

Minion
```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 3.4.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: raspbian 10 buster
        locale: UTF-8
       machine: armv7l
       release: 5.4.72-v7l+
        system: Linux
       version: Raspbian GNU/Linux 10 buster
```
Master
```
Salt Version:
           Salt: 3000.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  7 2020, 17:19:02)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.3.0
         system: Linux
        version: Ubuntu 16.04 xenial
```

### Pillar / config used

No pillar data for this test

---

### Describe the bug
Running `sudo salt-call state.apply docker` 
1 task fails with
```
----------
          ID: docker-software-service-running-docker
    Function: service.running
        Name: dockerd
      Result: False
     Comment: Service dockerd has been enabled, and is dead
     Started: 13:15:49.442715
    Duration: 2250.393 ms
     Changes:   
              ----------
              dockerd:
                  True
```
rebooting and then running `sudo /usr/local/bin/dockerd` causes `segmentation fault`

### Steps to reproduce the bug

1. Install salt-minion using bootstrap
2. reboot
3. run `sudo salt-call state.apply docker`

### Expected behaviour

I expect docker-service to be running.
