### ISSUE TITLE
Example to run a simple test sate

### ISSUE THREAD

**Issue by timorkal** [saltstack-formulas/docker-formula#272]
Hello,

I am new to salt and I try to run a simple salt state which installs docker and run simple nginx container.
I tried with the examples in formula main doc, but it seems that they are outdated as nothing works.

I am using SUSE Enterprise Linux 15.2 for both Master and Minion.
 
After playing around and reading this artcle:
https://docs.saltproject.io/en/latest/topics/development/conventions/formulas.html

I was able to get to a stage where it now says:
`
----------
          ID: test_docker
    Function: containers.running
        Name: nginx
      Result: False
     Comment: State 'containers.running' was not found in SLS 'test_docker'
              Reason: 'containers.running' is not available.
     Changes: `

This is my current slat state file:
```
---
include:
  - docker.software.service

test_docker:
  containers.running:
    - name: nginx
```

Please help.
