### ISSUE TITLE
[FEATURE] Manage "driver" and "driver_opts" in docker.networks.install state

### ISSUE THREAD

**Issue by kartnico** [saltstack-formulas/docker-formula#310]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Manage "driver" and "driver_opts" in [docker.networks.install state](https://github.com/saltstack-formulas/docker-formula/blob/master/docker/networks/install.sls)

Salt docker_network.present syntax1 :
```yaml
mynet:
  docker_network.present:
    - driver: macvlan
    - driver_opts: macvlan_mode=bridge,parent=eth0
```
Salt docker_network.present syntax2 :
```yaml
mynet:
  docker_network.present:
    - driver: macvlan
    - driver_opts:
      - macvlan_mode=bridge
      - parent=eth0
```

[Salt docker_network.present state](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.docker_network.html#salt.states.docker_network.present)
[Docker bridge driver options](https://docs.docker.com/engine/reference/commandline/network_create/#bridge-driver-options)

### Additional context
My use case is to manage "com.docker.network.bridge.name" driver_opts in order to rename bridge name
