### ISSUE TITLE
almalinux el9 [BUG] - deps fail to install (iptables)

### ISSUE THREAD

**Issue by ITJamie** [saltstack-formulas/docker-formula#328]
### Formula commit hash / release tag

latest git `da37c283c5ba4a37382dc0812cac196dc7b234b1`

### Versions reports (master & minion)

minion: 
```
Salt Version:
          Salt: 3006.1

Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 9.2 Turquoise Kodkod
        locale: utf-8
       machine: x86_64
       release: 5.14.0-284.11.1.el9_2.x86_64
        system: Linux
       version: AlmaLinux 9.2 Turquoise Kodkod
```

master:
```
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: 5.0.3
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.10.1
        Python: 3.8.10 (default, May 26 2023, 14:05:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1020-azure
        system: Linux
       version: Ubuntu 20.04 focal
```

### Pillar / config used
```
docker:
  pkg:
    docker:
      version: latest
      use_upstream: repo
    compose:
      version: 'latest'
      name: docker-compose
      commands:
        - docker-compose
      use_upstream: binary
      binary:
        source: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64

```

### Describe the bug
fails to install docker as it fails at the dependency stage
```
----------
          ID: docker-software-package-install-deps
    Function: pkg.installed
        Name: iptables
      Result: False
     Comment: The following packages failed to install/update: iptables
     Started: 12:09:50.758739
    Duration: 6086.56 ms
     Changes:
```

### Steps to reproduce the bug
clean install of almalinux 9
accept minion key
run `salt 'minion_id' state.sls docker`

### Expected behaviour
a clean install of docker-ce latest repo and its deps

### Attempts to fix the bug
none yet
