### ISSUE TITLE
Not clear how to use this

### ISSUE THREAD

**Issue by pwaller** [saltstack-formulas/docker-formula#5]
I get in principle that I should be able to add it to my `gitfs_remotes` and then `include` it, but I can't get it working.

In my master config:

``` yaml
fileserver_backend:
  - roots
  - git

gitfs_remotes:
  - https://github.com/saltstack-formulas/docker-formula
```

In my `devops-packages.sls`:

``` yaml
include:
  - docker
```

(I also tried docker.docker)

Then I ran:

```
sudo salt-call -l debug state.sls devops-packages
```

But I got:

```
Data failed to compile:
----------
    Specified SLS docker.docker in environment base is not available on the salt
 master
```
