### ISSUE TITLE
Add a list of user to group docker

### ISSUE THREAD

**Issue by toopy** [saltstack-formulas/docker-formula#52]
I we want to use docker with another user than `root`, we need to add it to the docker group outside of the formula. A conveniant way to do it could be to add to the docker group with the formula according to a list of users from pillars:

```
docker-users:
  lookup:
    names:
      - jenkins
      - ...
```
