### ISSUE TITLE
ENH: Utilize the docker HTTPS repository (apt-transport-https)

### ISSUE THREAD

**Issue by westurner** [saltstack-formulas/docker-formula#6]
Source: https://github.com/saltstack-formulas/docker-formula/blob/master/docker/init.sls#L14 :

```yaml
docker_repo:
    pkgrepo.managed:
      - repo: 'deb http://get.docker.io/ubuntu docker main'
      - file: '/etc/apt/sources.list.d/docker.list'
      - key_url: salt://docker/docker.pgp
```

Docs: https://get.docker.io/ubuntu/ :
```bash
# Check that HTTPS transport is available to APT
if [ ! -e /usr/lib/apt/methods/https ]; then
	apt-get update
	apt-get install -y apt-transport-https
fi
# Add the repository to your APT sources
echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
# Then import the repository key
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
# Install docker
apt-get update ; apt-get install -y lxc-docker

#
# Alternatively, just use the curl-able install.sh script provided at https://get.docker.io
#
```

- [ ] Change line 14 of docker/init.sls

````yaml
      - repo: 'deb https://get.docker.io/ubuntu docker main'
```

- [ ] Require pkg:apt-transport-https
  * https://github.com/saltstack-formulas/apt-formula/blob/master/apt/transports/https.sls
